# -*- coding: utf-8 -*-
"""Python topic base Projects.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpkKpg0qad8cfp4Hr3tFhERA52NLfGxG

#PROJECT 1: TEXT FORMATTER
# Module 1: Variables, Strings, Dicts
"""

def text_formatter_project():
    # Variables & Data Types
    name = "john doe"
    age = 25
    salary = 50000.50
    hobbies = ["reading", "coding", "gaming"]

    # String manipulation
    formatted_name = name.title()
    uppercase_name = name.upper()
    lowercase_name = name.lower()

    # String methods
    email = "  user@example.com  "
    clean_email = email.strip()

    # f-strings
    bio = f"Name: {formatted_name}, Age: {age}, Salary: ${salary:,.2f}"

    # Dictionary
    user_info = {
        'name': formatted_name,
        'age': age,
        'email': clean_email,
        'hobbies': hobbies
    }

    # String formatting
    print(f"Original: {name}")
    print(f"Formatted: {formatted_name}")
    print(f"Bio: {bio}")
    print(f"User Info: {user_info}")

    # Practice: Format a resume
    resume = f"""
{'='*40}
RESUME
{'='*40}
Name: {user_info['name'].upper()}
Email: {user_info['email']}
Hobbies: {', '.join(user_info['hobbies'])}
{'='*40}
    """.strip()

    print(resume)

"""#PROJECT 2: NUMBER ANALYZER
#Module 2: Loops, Conditionals
"""

def number_analyzer_project():

 numbers = [15, 22, 8, 45, 33, 12, 67, 89, 3, 50]

    # For loop - count evens and odds
    even_count = 0
    odd_count = 0

    for num in numbers:
        if num % 2 == 0:
            even_count += 1
        else:
            odd_count += 1

    print(f"Even numbers: {even_count}")
    print(f"Odd numbers: {odd_count}")

    # If/elif/else - categorize numbers
    categories = {'small': [], 'medium': [], 'large': []}

    for num in numbers:
        if num < 20:
            categories['small'].append(num)
        elif num < 50:
            categories['medium'].append(num)
        else:
            categories['large'].append(num)

    print(f"Categories: {categories}")

    # While loop - find sum
    total = 0
    index = 0

    while index < len(numbers):
        total += numbers[index]
        index += 1

    print(f"Total sum: {total}")

    # Nested loops - multiplication table
    print("\nMultiplication table (3x3):")
    for i in range(1, 4):
        for j in range(1, 4):
            print(f"{i} x {j} = {i*j}", end="  |  ")
        print()

"""# PROJECT 3: GRADE CALCULATOR
# Module 3: Functions, Lambda
"""

def grade_calculator_project():



# Regular function
    def calculate_average(scores):

        return sum(scores) / len(scores)

    # Function with multiple parameters
    def get_grade(score):

        if score >= 90:
            return 'A'
        elif score >= 80:
            return 'B'
        elif score >= 70:
            return 'C'
        elif score >= 60:
            return 'D'
        else:
            return 'F'

    # Function with default parameter
    def format_result(name, grade, passed=True):
        status = "PASSED" if passed else "FAILED"
        return f"{name}: Grade {grade} - {status}"

    # Lambda functions
    add_bonus = lambda score: score + 5
    is_passing = lambda score: score >= 60

    # Using map with lambda
    scores = [85, 92, 78, 65, 88]
    scores_with_bonus = list(map(add_bonus, scores))

    # Using filter with lambda
    passing_scores = list(filter(is_passing, scores))

    # Putting it together
    student_name = "Alice"
    avg_score = calculate_average(scores)
    final_grade = get_grade(avg_score)

    print(f"Original scores: {scores}")
    print(f"With bonus: {scores_with_bonus}")
    print(f"Passing scores: {passing_scores}")
    print(f"Average: {avg_score:.2f}")
    print(format_result(student_name, final_grade, avg_score >= 60))

"""# PROJECT 4: DATA TRANSFORMER
# Module 4: Comprehensions
"""

def data_transformer_project():

    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    names = ["alice", "bob", "charlie", "david"]
    prices = [10.5, 20.0, 15.75, 30.25]

    # List comprehension - squares
    squares = [num ** 2 for num in numbers]
    print(f"Squares: {squares}")

    # List comprehension with condition - even numbers
    evens = [num for num in numbers if num % 2 == 0]
    print(f"Even numbers: {evens}")

    # List comprehension with transformation
    capitalized = [name.upper() for name in names]
    print(f"Capitalized: {capitalized}")

    # Dictionary comprehension
    name_lengths = {name: len(name) for name in names}
    print(f"Name lengths: {name_lengths}")

    # Dictionary comprehension with condition
    long_names = {name: len(name) for name in names if len(name) > 4}
    print(f"Long names: {long_names}")

    # Set comprehension - unique first letters
    first_letters = {name[0].upper() for name in names}
    print(f"First letters: {first_letters}")

    # Nested comprehension - matrix
    matrix = [[i*j for j in range(1, 4)] for i in range(1, 4)]
    print(f"Matrix: {matrix}")

    # Combining lists into dict
    price_dict = {names[i]: prices[i] for i in range(len(names))}
    print(f"Price dictionary: {price_dict}")

"""

# PROJECT 5: SIMPLE BANK
# Module 5: Basic OOP"""

def simple_bank_project():

 # Basic class
    class BankAccount:

        # Class variable
        bank_name = "MyBank"
        total_accounts = 0

        def __init__(self, owner, balance=0):
            """Constructor"""
            self.owner = owner
            self.balance = balance
            self.transactions = []
            BankAccount.total_accounts += 1

        def deposit(self, amount):
            """Instance method"""
            self.balance += amount
            self.transactions.append(f"Deposit: +${amount}")
            return self.balance

        def withdraw(self, amount):
            """Instance method with validation"""
            if amount > self.balance:
                return "Insufficient funds"
            self.balance -= amount
            self.transactions.append(f"Withdraw: -${amount}")
            return self.balance

        def get_info(self):
            """Return account info"""
            return f"{self.owner}'s Account: ${self.balance}"

        @classmethod
        def get_bank_name(cls):
            """Class method"""
            return cls.bank_name

        @staticmethod
        def is_valid_amount(amount):
            """Static method"""
            return amount > 0

        def __str__(self):
            """String representation"""
            return f"Account({self.owner}, ${self.balance})"

        def __repr__(self):
            """Developer representation"""
            return f"BankAccount(owner='{self.owner}', balance={self.balance})"

    # Create accounts
    acc1 = BankAccount("Alice", 1000)
    acc2 = BankAccount("Bob", 500)

    # Use methods
    print(acc1.get_info())
    acc1.deposit(200)
    print(f"After deposit: {acc1.get_info()}")

    acc1.withdraw(150)
    print(f"After withdrawal: {acc1.get_info()}")

    # Class method and static method
    print(f"Bank: {BankAccount.get_bank_name()}")
    print(f"Total accounts: {BankAccount.total_accounts}")
    print(f"Is $50 valid? {BankAccount.is_valid_amount(50)}")

    # String representations
    print(f"str: {str(acc1)}")
    print(f"repr: {repr(acc1)}")

    # Transactions
    print(f"Transactions: {acc1.transactions}")

"""# PROJECT 6: VEHICLE SYSTEM
# Module 6: Advanced OOP
"""

def vehicle_system_project():
  class Vehicle:
        """Base vehicle class"""

        def __init__(self, brand, model, year):
            self._brand = brand  # Protected
            self.__model = model  # Private
            self._year = year

        @property
        def brand(self):
            """Property getter"""
            return self._brand

        @brand.setter
        def brand(self, value):
            """Property setter with validation"""
            if len(value) < 2:
                raise ValueError("Brand must be at least 2 characters")
            self._brand = value

        @property
        def model(self):
            """Getter for private attribute"""
            return self.__model

        def get_info(self):
            """Method to be overridden"""
            return f"{self._year} {self._brand} {self.__model}"

        def start(self):
            """Common method"""
            return "Vehicle started"

    # Inheritance - Car
  class Car(Vehicle):
        """Car inherits from Vehicle"""

        def __init__(self, brand, model, year, doors):
            super().__init__(brand, model, year)
            self.doors = doors

        def get_info(self):
            """Override parent method - Polymorphism"""
            base_info = super().get_info()
            return f" Car: {base_info}, {self.doors} doors"

        def start(self):
            """Override with different behavior"""
            return "Car engine started with key"

    # Inheritance - Motorcycle
  class Motorcycle(Vehicle):
        """Motorcycle inherits from Vehicle"""

        def __init__(self, brand, model, year, engine_cc):
            super().__init__(brand, model, year)
            self.engine_cc = engine_cc

        def get_info(self):
            """Override parent method - Polymorphism"""
            base_info = super().get_info()
            return f"  Motorcycle: {base_info}, {self.engine_cc}cc"

        def start(self):
            """Override with different behavior"""
            return "Motorcycle started with kick"

    # Create objects
  car = Car("Toyota", "Camry", 2024, 4)
  bike = Motorcycle("Honda", "CBR", 2024, 1000)

    # Polymorphism - same method, different behavior
  vehicles = [car, bike]

  print("Vehicle Information:")
  for vehicle in vehicles:
        print(f"  {vehicle.get_info()}")
        print(f"  {vehicle.start()}")

    # Property usage
  print(f"\nCar brand: {car.brand}")
  car.brand = "Honda"
  print(f"Updated brand: {car.brand}")

    # Accessing through property
  print(f"Car model: {car.model}")

"""# PROJECT 7: NOTE SAVER
# Module 7: File I/O, JSON
"""

import json
import os


# Create notes
    notes = [
        {"id": 1, "title": "Shopping List", "content": "Milk, Eggs, Bread"},
        {"id": 2, "title": "Ideas", "content": "Learn Python, Build app"},
        {"id": 3, "title": "Todo", "content": "Finish homework"}
    ]

    # Save to JSON file
    with open("notes.json", "w") as f:
        json.dump(notes, f, indent=2)
    print(" Saved to notes.json")

    # Load from JSON file
    with open("notes.json", "r") as f:
        loaded_notes = json.load(f)
    print(f" Loaded {len(loaded_notes)} notes")

    # Save to text file
    with open("notes.txt", "w") as f:
        f.write("MY NOTES\n")
        f.write("="*40 + "\n\n")
        for note in notes:
            f.write(f"[{note['id']}] {note['title']}\n")
            f.write(f"    {note['content']}\n\n")
    print(" Saved to notes.txt")

    # Read from text file
    with open("notes.txt", "r") as f:
        content = f.read()
    print("\n Text file content:")
    print(content)

    # Append to file
    with open("notes.txt", "a") as f:
        f.write("\n--- End of Notes ---\n")
    print(" Appended to notes.txt")

    # Check if file exists
    if os.path.exists("notes.json"):
        print(" notes.json exists")
        # Get file size
        size = os.path.getsize("notes.json")
        print(f" File size: {size} bytes")

"""# PROJECT 8: TEXT EXTRACTOR
# Module 8: Regex, Collections
"""

import re
from collections import Counter

def text_extractor_project():

    # Sample text
    text = """
    Contact us at support@company.com or sales@company.com
    Call us at 123-456-7890 or 098-765-4321
    Visit on 25/10/2025 or 30/12/2025
    #python #coding #learning
    Important: URGENT task must be done ASAP!
    """

    # Extract emails
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    emails = re.findall(email_pattern, text)
    print(f" Emails found: {emails}")

    # Extract phone numbers
    phone_pattern = r'\b\d{3}-\d{3}-\d{4}\b'
    phones = re.findall(phone_pattern, text)
    print(f" Phones found: {phones}")

    # Extract dates
    date_pattern = r'\b\d{2}/\d{2}/\d{4}\b'
    dates = re.findall(date_pattern, text)
    print(f"Dates found: {dates}")

    # Extract hashtags
    hashtag_pattern = r'#\w+'
    hashtags = re.findall(hashtag_pattern, text)
    print(f" Hashtags found: {hashtags}")

    # Extract capital words
    capital_words = re.findall(r'\b[A-Z]{2,}\b', text)
    print(f" Capital words: {capital_words}")

    # Word frequency using Counter
    words = re.findall(r'\b\w+\b', text.lower())
    word_counts = Counter(words)
    print(f"\n Most common words:")
    for word, count in word_counts.most_common(5):
        print(f"   {word}: {count}")

    # Count hashtags
    hashtag_counts = Counter(hashtags)
    print(f"\n Hashtag counts: {hashtag_counts}")

    # Replace pattern
    censored = re.sub(r'\d{3}-\d{3}-\d{4}', '[REDACTED]', text)
    print(f"\n Censored text (phones hidden):")
    print(censored[:100] + "...")

"""# PROJECT 9: LOTTERY SIMULATOR
# Module 9: Random Modul
"""

import random

def lottery_simulator_project():

    # random.randint - generate random integers
    lucky_number = random.randint(1, 100)
    print(f" Your lucky number: {lucky_number}")

    # random.choice - pick one item
    colors = ["Red", "Blue", "Green", "Yellow", "Purple"]
    lucky_color = random.choice(colors)
    print(f" Your lucky color: {lucky_color}")

    # random.sample - pick multiple unique items
    lottery_numbers = random.sample(range(1, 50), 6)
    lottery_numbers.sort()
    print(f"Lottery numbers: {lottery_numbers}")

    # random.shuffle - shuffle list in place
    deck = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]
    random.shuffle(deck)
    print(f" Shuffled deck: {deck[:5]}...")

    # random.random - float between 0 and 1
    probability = random.random()
    print(f" Random probability: {probability:.2f}")

    # random.uniform - float in range
    temperature = random.uniform(20.0, 30.0)
    print(f" Random temperature: {temperature:.1f}°C")

    # random.choices - pick with replacement
    dice_rolls = random.choices(range(1, 7), k=10)
    print(f" 10 dice rolls: {dice_rolls}")

    # Simulate coin flips
    flips = [random.choice(["Heads", "Tails"]) for _ in range(10)]
    heads = flips.count("Heads")
    print(f" Coin flips: {heads} heads, {10-heads} tails")

    # Random password generator
    chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    password = ''.join(random.choices(chars, k=8))
    print(f" Random password: {password}")

"""# PROJECT 10: SAFE CALCULATOR
# Module 10: Error Handling
"""

def safe_calculator_project():
    # Basic try-except
    def safe_divide(a, b):
        """Divide with error handling"""
        try:
            result = a / b
            return result
        except ZeroDivisionError:
            print(" Error: Cannot divide by zero!")
            return None
        except TypeError:
            print("Error: Invalid input types!")
            return None

    print(f"10 / 2 = {safe_divide(10, 2)}")
    print(f"10 / 0 = {safe_divide(10, 0)}")

    # Try-except-else
    def safe_sqrt(n):
        """Square root with validation"""
        try:
            if n < 0:
                raise ValueError("Cannot calculate square root of negative number")
            result = n ** 0.5
        except ValueError as e:
            print(f" Error: {e}")
            return None
        else:
            print(f" Calculation successful")
            return result

    print(f"√16 = {safe_sqrt(16)}")
    print(f"√-4 = {safe_sqrt(-4)}")

    # Try-except-finally
    def read_number_from_file(filename):
        """Read with cleanup"""
        try:
            f = open(filename, 'r')
            content = f.read()
            number = int(content)
            return number
        except FileNotFoundError:
            print(f" File {filename} not found")
            return None
        except ValueError:
            print(f" File content is not a number")
            return None
        finally:
            print(f"Cleanup: Attempted to read {filename}")
            try:
                f.close()
            except:
                pass

    # Custom exception
    class NegativeNumberError(Exception):
        """Custom exception for negative numbers"""
        pass

    def positive_only(n):
        """Only accept positive numbers"""
        try:
            if n < 0:
                raise NegativeNumberError(f"Number {n} is negative!")
            return n * 2
        except NegativeNumberError as e:
            print(f" {e}")
            return None

    print(f"5 * 2 = {positive_only(5)}")
    print(f"-3 * 2 = {positive_only(-3)}")

    # Multiple exceptions
    def safe_operation(a, b, operation):
        """Perform operation safely"""
        try:
            if operation == "divide":
                return a / b
            elif operation == "power":
                return a ** b
            else:
                raise ValueError(f"Unknown operation: {operation}")
        except ZeroDivisionError:
            return "Error: Division by zero"
        except OverflowError:
            return "Error: Result too large"
        except ValueError as e:
            return f"Error: {e}"
        except Exception as e:
            return f"Unexpected error: {e}"

    print(f"10 / 2 = {safe_operation(10, 2, 'divide')}")
    print(f"10 / 0 = {safe_operation(10, 0, 'divide')}")
    print(f"999 ** 999 = {safe_operation(999, 999, 'power')}")

"""# PROJECT 11: TIMING DECORATOR
# Module 11: Decorators
"""

import time
from functools import wraps

def timing_decorator_project():
    # Basic decorator
    def timer(func):
        """Measure function execution time"""
        @wraps(func)
        def wrapper(*args, **kwargs):
            start = time.time()
            result = func(*args, **kwargs)
            end = time.time()
            print(f" {func.__name__} took {end - start:.4f}s")
            return result
        return wrapper

    # Decorator with logging
    def logger(func):
        """Log function calls"""
        @wraps(func)
        def wrapper(*args, **kwargs):
            print(f"Calling {func.__name__}()")
            result = func(*args, **kwargs)
            print(f"{func.__name__}() completed")
            return result
        return wrapper

    # Decorator for validation
    def validate_positive(func):
        """Validate positive numbers"""
        @wraps(func)
        def wrapper(n):
            if n < 0:
                raise ValueError("Number must be positive")
            return func(n)
        return wrapper

    # Using decorators
    @timer
    def slow_function():
        """Simulate slow operation"""
        time.sleep(0.1)
        return "Done"

    @logger
    @timer
    def calculate_sum(n):
        """Calculate sum with multiple decorators"""
        time.sleep(0.05)
        return sum(range(n))

    @validate_positive
    def square_root(n):
        """Calculate square root"""
        return n ** 0.5

    # Test decorated functions
    print("Testing decorated functions:\n")

    result1 = slow_function()
    print(f"Result: {result1}\n")

    result2 = calculate_sum(1000)
    print(f"Sum: {result2}\n")

    try:
        result3 = square_root(16)
        print(f"√16 = {result3}")
        result4 = square_root(-4)  # Will raise error
    except ValueError as e:
        print(f"Error: {e}")

    # Decorator with arguments
    def repeat(times):
        """Decorator that repeats function"""
        def decorator(func):
            @wraps(func)
            def wrapper(*args, **kwargs):
                results = []
                for _ in range(times):
                    result = func(*args, **kwargs)
                    results.append(result)
                return results
            return wrapper
        return decorator

    @repeat(times=3)
    def greet(name):
        """Greet someone"""
        return f"Hello, {name}!"

    print(f"\nRepeated greeting: {greet('Alice')}")

"""Prakash Saha Roy collection

```
# https://www.linkedin.com/in/prakash-saha-roy-452396281/

```


"""